[package]
name = "par-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { version = "0.3.31", features = ["executor", "thread-pool"] }
pest = "2.7.14"
pest_derive = "2.7.14"
eframe = { version = "0.31", features = ["default", "__screenshot"] }
egui_code_editor = "0.2.12"
indexmap = "2.7.0"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"] }
stacker = "0.1.19"
async-watch = "0.3.1"
rfd = "0.15.2"
winnow = { version = "0.7.4", features = [
    #"unstable-doc", # build docs locally
    #"debug" # debug output/state of parser
] }
miette = { version = "7.5.0", features = ["fancy"] }
